Repository nanoc/nanoc, pull requests merged in 2018-10, with the labels that each got.

#1360 Validate configuration
  nanoc/lib/nanoc.rb
  nanoc/lib/nanoc/base/core_ext/array.rb
  nanoc/lib/nanoc/base/core_ext/hash.rb
  nanoc/lib/nanoc/base/entities/configuration-schema.json
  nanoc/lib/nanoc/base/entities/configuration.rb
  nanoc/lib/nanoc/cli/error_handler.rb
  nanoc/nanoc.gemspec
  nanoc/spec/nanoc/base/core_ext/array_spec.rb
  nanoc/spec/nanoc/base/core_ext/hash_spec.rb
  nanoc/spec/nanoc/base/entities/configuration_spec.rb
  nanoc/spec/nanoc/cli/error_handler_spec.rb
  nanoc/spec/nanoc/regressions/gh_1352_spec.rb
  nanoc/test/checking/checks/test_stale.rb
Labels: type:enhancement :sparkles:

#1370 Raise when meta-file cannot be unambiguously associated
  nanoc/lib/nanoc/base/errors.rb
  nanoc/lib/nanoc/data_sources/filesystem.rb
  nanoc/lib/nanoc/data_sources/filesystem/parser.rb
  nanoc/spec/nanoc/data_sources/filesystem_spec.rb
Labels: type:bug :bug:

#1365 Sass improvements
  common/spec/spec_helper_foot.rb
  nanoc/lib/nanoc/base/services/filter.rb
  nanoc/lib/nanoc/filters/sass.rb
  nanoc/lib/nanoc/filters/sass/sass_filesystem_importer.rb
  nanoc/nanoc.manifest
  nanoc/spec/nanoc/filters/sass_spec.rb
Labels: type:feature :gift:

#1371 Lazy-load Sass
  nanoc/lib/nanoc/filters/sass.rb
  nanoc/lib/nanoc/filters/sass/functions.rb
  nanoc/lib/nanoc/filters/sass/importer.rb
  nanoc/nanoc.manifest
  nanoc/spec/nanoc/cli/error_handler_spec.rb
  nanoc/spec/nanoc/filters/sass_spec.rb
Labels: type:bug :bug:

#1373 Let RulesModified check dependent objects as well
  nanoc/lib/nanoc/base/services/outdatedness_rules/rules_modified.rb
  nanoc/spec/nanoc/base/services/outdatedness_rules_spec.rb
  nanoc/spec/nanoc/regressions/gh_1372_spec.rb
Labels: type:bug :bug:

#1375 Let `write nil` always skip routing rule
  nanoc/lib/nanoc/base/entities/processing_actions/snapshot.rb
  nanoc/lib/nanoc/rule_dsl/action_recorder.rb
  nanoc/lib/nanoc/rule_dsl/action_sequence_calculator.rb
  nanoc/spec/nanoc/integration/write_nil_spec.rb
  nanoc/spec/nanoc/regressions/gh_1374_spec.rb
  nanoc/spec/nanoc/rule_dsl/action_recorder_spec.rb
Labels: type:bug :bug:
