Repository nanoc/nanoc, pull requests merged in 2019-08, with the labels that each got.

#1447 Let #find_all yield item views, not item objects
  nanoc/lib/nanoc/base/views/identifiable_collection_view.rb
  nanoc/spec/nanoc/base/views/support/identifiable_collection_view_examples.rb
Labels: type:bug :bug:

#1438 Allow specifying excluded files across all checks
  nanoc-core/lib/nanoc/core/configuration-schema.json
  nanoc-core/spec/nanoc/core/configuration_spec.rb
  nanoc/lib/nanoc/checking/check.rb
  nanoc/spec/nanoc/checking/check_spec.rb
Labels: type:enhancement :sparkles:

#1443 Replace handlebars.rb with ruby-handlebars
  Gemfile
  nanoc/lib/nanoc/cli/error_handler.rb
  nanoc/lib/nanoc/filters/handlebars.rb
Labels: type:enhancement :sparkles:

#1452 Fix dependency tracking for sass imports
  nanoc/lib/nanoc/filters/sass/importer.rb
Labels: component:filter, type:enhancement :sparkles:
